services:
  db:
    image: mysql
    container_name: hotel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: hotel
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-app
    tty: true
    depends_on:
      - db
    ports:
      - '8080:8080'
    links:
      - 'db:database'
